# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29faea38498985f86af7dd2ae36aaae40fe1c3f48ff951e11aed714f6fdf97e478ffac3d7671ad1fa9829e3723ebb64d241ad2ff359396d543c0598c9500410

test:
  secret_key_base: aa66120d0709c520e3edd55e572eeafc60d570bb372a41d31c8a157644804766229721b2458e7d39e0938f55e2e92c72ea37031cdca45c67a143eeef8bee3a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
